Border on details page
zara19013/flags-project pull request #14
Opened 2023-08-30 10:50 UTC by zara19013

borders country details fetch and display

2023-08-30 12:51 UTC, asad-shayansolution commented on src/App.js
> +            </Routes>
Use prettier extension and format your code before commit

2023-08-30 12:53 UTC, asad-shayansolution approved these changes
ok

2023-08-30 12:53 UTC, asad-shayansolution commented on src/components/homepage/filter.css
> +.FilterBox {
why these classname are capital?

2023-08-30 13:00 UTC, imran-munawar requested changes

2023-08-30 13:00 UTC, imran-munawar commented on src/components/Detail/Detail.js
> +              `https://restcountries.com/v3.1/alpha/${borderCountryCode}`
add base URL in env

2023-08-30 13:06 UTC, zara19013 commented on src/App.js
> +            </Routes>
ok

2023-08-30 13:07 UTC, zara19013 commented on src/components/homepage/filter.css
> +.FilterBox {
i don't get your point!

2023-08-31 06:09 UTC, asad-shayansolution approved these changes

2023-08-31 07:23 UTC, imran-munawar approved these changes

2023-08-31 07:37 UTC, merged